name: CI-Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    permissions:
      id-token: write # Needed to pick up on signing with a GitHub workflow identity.
    steps:
      - uses: meta-introspector/checkout@main # v4.1.2
      - uses: meta-introspector/setup-go@main # v5.0.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Run Go tests
        # cannot run tests with race because we are mutating state (setting ENV variables)
        run: GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} go test -covermode=atomic  -coverprofile=unit-coverage.out ./...
      - name: Upload codecoverage
        uses: meta-introspector/codecov-action@main # v3.1.6
        with:
         files: ./unit-coverage.out
         verbose: true

  verify:
    name: Run verify
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: meta-introspector/checkout@main # v4.1.2
      - uses: meta-introspector/setup-go@main # v5.0.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Run Go verify
        run: |
            go mod tidy && go mod verify
            git diff --exit-code
